name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '*/15 * * * *'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      IS_EMERYNET_TEST: ${{ github.event_name == 'schedule' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 'GCP auth'
        uses: 'google-github-actions/auth@v2'
        if: env.IS_EMERYNET_TEST
        with:
          project_id: 'simulationlab'
          workload_identity_provider: 'projects/60745596728/locations/global/workloadIdentityPools/github/providers/dapp-econ-gov'

      - name: Run e2e tests
        id: e2e_test
        run: |
          docker-compose -f tests/e2e/docker-compose.yml --profile $SYNPRESS_PROFILE up --build --exit-code-from synpress
        env:
          # conditionals based on github event
          SYNPRESS_PROFILE: ${{ env.IS_EMERYNET_TEST && 'daily-tests' || 'synpress' }}
          CYPRESS_AGORIC_NET: ${{ env.IS_EMERYNET_TEST && 'emerynet' || 'local' }}
          # for docker-compose.yml
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          DOCKER_DEFAULT_PLATFORM: linux/amd64
          NGROK_AUTH: ${{ secrets.NGROK_AUTH }}
          NGROK_BASIC_AUTH: ${{ secrets.NGROK_BASIC_AUTH }}
          CYPRESS_PRIVATE_KEY_WITH_FUNDS: ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GOV1_PHRASE: ${{ secrets.GOV1_PHRASE }}
          GOV2_PHRASE: ${{ secrets.GOV2_PHRASE }}
          # cypress dashboard
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Debug Log
        if: always()
        run: |
          echo "${{ !env.IS_EMERYNET_TEST && !cancelled() && steps.e2e_test.outcome == 'success' }} ${{ env.IS_EMERYNET_TEST && !cancelled() && steps.e2e_test.outcome == 'success' }}"
          
      - name: Archive e2e artifacts locally
        uses: actions/upload-artifact@v3
        if: ${{ !env.IS_EMERYNET_TEST  && !cancelled() && steps.e2e_test.outcome == 'success' }}
        with:
          name: e2e-artifacts
          path: |
            tests/e2e/docker/videos
            tests/e2e/docker/screenshots
        continue-on-error: true

      - name: Archive e2e artifacts to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        if: ${{ env.IS_EMERYNET_TEST && !cancelled() && steps.e2e_test.outcome == 'success' }}
        with:
          path: 'tests/e2e/docker'
          destination: 'github-artifacts/${{ github.repository }}/${{ github.run_id }}/${{ github.event.repository.updated_at }}'
        continue-on-error: true

      - name: Log Path to GCS Artifacts
        if: env.IS_EMERYNET_TEST
        run: echo "https://console.cloud.google.com/storage/browser/github-artifacts/${{ github.repository }}/${{ github.run_id }}/${{ github.event.repository.updated_at }}/docker/videos"
